on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on:


    steps:  ubuntu-latest
      - name: 'Testing Github action'
        run: pwd

      - name: 'Testing printing'
        run: echo Areej
