on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest


    steps: 
      - name: 'printing folder contens'
        run: ls

      - name: 'Testing printing'
        run: echo Areej
